---
loader: taskgraph.loader.transform:loader

transforms:
  - src.transforms:taskcluster_images
  - src.transforms:add_task_env
  - taskgraph.transforms.job:transforms
  - taskgraph.transforms.task:transforms

job-defaults:
  worker-type: ci
  run:
    using: bare
  worker:
    max-run-time: 600
    docker-image: {taskcluster: 'browser-test'}

jobs:
  browser-test:
    description: UI Browser Tests
    run:
      install: >-
         {{ yarn --frozen-lockfile || exit 99; }} &&
         cd ui &&
         {{ yarn --frozen-lockfile || exit 99; }}
      command: >-
         yarn lint &&
         {{ Xvfb :99 -screen 0 640x480x8 -nolisten tcp & }} &&
         sleep 2 &&
         CHROME_BIN=firefox DISPLAY=:99 yarn test
