defaults:
  app:
    workerTableName: wmworkers_entities
    workerPoolTableName: wmworker_pools_entities
    workerPoolErrorTableName: wmworker_pool_errors_entities
    errorsExpirationDelay: '-4 days' # Anything older than a few days goes away
    provisionerIterateConfig: !env:json:optional PROVISIONER_ITERATE_CONFIG
    workerScannerIterateConfig: !env:json:optional WORKER_SCANNER_ITERATE_CONFIG
  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:optional ERROR_CONFIG
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
  azure:
    accountId: !env AZURE_ACCOUNT_ID
  postgres:
    readDbUrl: !env READ_DB_URL
    writeDbUrl: !env WRITE_DB_URL
    dbCryptoKeys: !env:json:optional DB_CRYPTO_KEYS
  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
  pulse:
    hostname: !env PULSE_HOSTNAME
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
    vhost: !env PULSE_VHOST
  providers: !env:json PROVIDERS

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:optional NEW_RELIC

test:
  server:
    port: 60409
    env: 'development'
    forceSSL: false
    trustProxy: false
  taskcluster:
    rootUrl: "https://tc.example.com"
  azure:
    accountId: "pamplemousse"
  app:
    errorsExpirationDelay: '-1 hour'
  postgres:
    dbCryptoKeys:
      - id: 'worker-manager'
        algo: 'aes-256'
        key: "aSdtIGJzdGFjayEgaGVsbG8gZnV0dXJlIHBlcnNvbgo="
  providers:
    testing1:
      providerType: testing
    testing2:
      providerType: testing
    static:
      providerType: static
    google:
      providerType: google
      project: testy
      creds: {client_id: "fake-creds"}
      workerServiceAccountId: 12345
    aws:
      providerType: aws
    azure:
      providerType: azure
      secret: 123abc
      clientId: my client
      domain: a domain
      resourceGroupName: some resources
