$schema: "/schemas/common/metaschema.json#"
title: Azure Provider Config
description: |
  'The config section of a workertype is using a provider with implementation azure must match this.
  Much of these fields are documented [here](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate)'
type: object
properties:
  minCapacity:
    title: Minimum Capacity
    type: integer
    minimum: 0
    description: |
      The minimum amount of capacity that worker-manager should make
      available at any given time.
  maxCapacity:
    title: Maximum Capacity
    type: integer
    minimum: 0
    description: |
      The maximum amount of capacity that worker-manager should make
      available at any given time.
  lifecycle: {$ref: 'worker-lifecycle.json#'}
  launchConfigs:
    type: array
    title: Choices
    description: |
      An array of possible variations of workers for this pool.
      Each choice must include at least the required properties but can also include anything in
      the request body of [the virtual machine creation](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate)
      api method. worker-manager sets the values of the `osProfile.adminPassword`, `osProfile.computerName`, `osProfile.customData`, `networkProfile.networkInterfaces`
      properties directly, and they cannot be overriden. It also fills in some basic labels, will generate a default description, and sets the `taskcluster`
      metadata key directly. You are free to set other metadata items though. A subset of these fields we require you to set such as `machineType`.
    uniqueItems: false
    items:
      type: object
      properties:
        capacityPerInstance:
          title: Capacity Per Instance
          type: integer
          minimum: 1
          description: The number of tasks a single worker of this type can run at any given time.
        workerConfig:
          title: Worker Config
          type: object
          additionalProperties: true
          description: |
            This value is supplied unchanged as the `workerConfig` property of the `taskcluster` instance metadata attribute.
            The expectation is that the worker will merge this information with configuration from other sources,
            and this is precisely what [worker-runner](https://github.com/taskcluster/taskcluster/tree/master/tools/worker-runner) does.
            This property must not be used for secret configuration, as it is visible both in the worker pool configuration and in the worker instance's metadata.
            Instead, put secret configuration in the [secrets service](https://github.com/taskcluster/taskcluster/tree/master/tools/worker-runner#secrets).
        location:
          title: Location
          type: string
          description: The Azure location this worker should be spawned in
        subnetId:
          title: Subnet ID
          type: string
          description: The ID of the subnet workers should be spawned in
        priority:
          title: Priority
          type: string
          description: |
            virtual machine priority, i.e. Spot
            https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#virtualmachineprioritytypes
        billingProfile:
          title: Billing Profile
          type: object
          description: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#billingprofile
          additionalProperties: true
          required: []
          properties:
            maxPrice:
              title: Max Price
              type: number
              description: the maximum price to pay for a spot virtual machine in US Dollars
        hardwareProfile:
          title: Hardware Profile
          type: object
          description: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#hardwareprofile
          additionalProperties: true
          required:
            - vmSize
          properties:
            vmSize:
              title: Virtual machine type
              type: string
        osProfile:
          title: OS Profile
          type: object
          description: |
            adminPassword, computerName, and customData are set by the provider and are not configurable
            https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#osprofile
          additionalProperties: true
          required: []
        storageProfile:
          title: Storage Profile
          type: object
          additionalProperties: true
          required:
            - osDisk
          properties:
            osDisk:
              title: OS Disk
              type: object
              description: |
                Naming disks is not supported.
                https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#osdisk
              additionalProperties: true
              required: []
              properties:
                createOption:
                  type: string
                  description: |
                    FromImage creates the disk from the specified image
                    https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#diskcreateoptiontypes
            imageReference:
              description: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#imagereference
              type: object
              additionalProperties: true
              required: []
              properties:
                id:
                  type: string
        networkProfile:
          title: Network Profile
          type: object
          description: |
            Container object for network interfaces for the VM
            See here: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#networkprofile
          additionalProperties: true
          required:
            - networkInterfaces
          properties:
            networkInterfaces:
              title: Network Interfaces
              type: array
              uniqueItems: false
              items:
                title: Network Interface Reference
                type: object
                additionalProperties: true
                required: []
                properties:
                  id:
                    type: string
                  primary:
                    type: boolean
      required:
        - capacityPerInstance
        - workerConfig
        - location
        - subnetId
        - hardwareProfile
        - storageProfile
      additionalProperties: true
additionalProperties: false
required:
  - minCapacity
  - maxCapacity
  - launchConfigs
